---
title: ""
runningheader: "COMM 7018 Social Media Theory" # only for pdf output
subtitle: "" # only for html output
author: "Martin Roberts"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html:
    tufte_variant: "envisioned"
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
link-citations: yes
---

# COMM 7018: SOCIAL MEDIA THEORY  
Fitchburg State University  
Communications Media Department  
MS in Applied Communication: Social Media Concentration  

Schedule: Monday 16 May – Monday 4 July 2022  
Instructor: Dr. Martin Roberts  
Contact: [email](mailto:mrober40@fitchburgstate.edu)    

***  

## OVERVIEW  
The term **social media** is popularly understood as referring to corporate-owned, advertising-funded communication **platforms** based on **user-generated content**: YouTube, Instagram, Facebook, Twitter, Twitch, Discord, TikTok. It can also be defined more broadly, however, as a set of networked, technologically-mediated  **practices** of communication, structured by economic and political forces that both inflect and are inflected by social and cultural identities. These platforms, the social practices that they enable, and the relationship between the two are the objects of **social media theory**. But what does it mean to **theorize** social media? Why do we need social media theory at all?

To theorize something involves a number of processes:

- first, how do we define the phenomenon or object of study itself? How does it differ from previous or other related phenomena?
- how are we to account for it? Why did it happen/is it happening now rather than at some other time? What are its conditions of possibility?
- what is its relation to larger areas of society? What are its implications for those areas?
- how are we to evaluate it, in terms of its implications (political, economic, social, ethical, legal, environmental, aesthetic)? What are its possibilities and limits, its progressive and oppressive aspects? How can we change it for the better?

These processes involve developing analytical frameworks or models comprising concepts that are useful for identifying and analyzing key aspects of and issues raised by the phenomenon/object in question. These frameworks and concepts typically draw from existing ones in different fields of study, but often involve the proposal of new frameworks and concepts specific to the field in question.

We begin by defining the object itself: what exactly do we mean by the term **social media**? Haven't **media** - whether in the ancient or modern sense - always already been **social**? How do **social media** platforms differ from **social networking** platforms? What is a **platform** anyway, and how does it differ from a **medium**? 

We then consider each week some of the key dimensions of social media communication:

- the dimension of **sharing** that is arguably the central practice of social media;
- the **affective** or emotionally-expresssive dimension of social media, i.e. their role in articulating and sharing **structures of feeling**;
- the role of **language** in social media and its transformation;
the concept of the **attention economy** that is the economic basis for commercial social media platforms;
- the notion of social media as a complex **ecosystem** of interdependent practices, as well as proposals for addressing toxic elements within this ecosystem;
- finally, we consider possible **futures** of social media and both their potentially progressive and harmful implications as a site of struggle between competing forces and interests in the years ahead. 


## OBJECTIVES  
By the end of the course, students will be able to:

- analyze technologies past, present, and imagined
- describe the ways in which technologies shape our world the ways in which we shape those technologies
- explain how social media is a result of the intersection between technologies and existing human communication dynamics
- discuss how theory of technology and social media can improve the vocational outlook of a student
- play a productive role in and even facilitate conversations that tease out the relationships between values and technology.  
- through the skills you will refine in writing your research papers, clearly explain how a specific technology shapes the social world that we live in.  

***  

## COURSE READINGS  

**Required**  

- Nicholas A. John, _The Age of Sharing_. Cambridge: Polity Press, 2016.   
- [Gretchen McCulloch](https://gretchenmcculloch.com/), [_Because Internet: Understanding the New Rules of Language_](https://gretchenmcculloch.com/book/). Riverhead Books, 2019.   

**Other sources**  
These sources are either freely available online or excerpts will be posted on Blackboard.  

- Yves Citton, _The Ecology of Attention_. Cambridge: Polity Press, 2017 [French edition: _Pour une écologie de l'attention_, Éditions du Seuil, 2014].   
- Adam D.I. Kramer, Jamie E. Guillory, and Jeffrey T. Hancock, "[Experimental evidence of massive-scale emotional contagion through social networks](https://doi.org/10.1073/pnas.1320040111)," _PNAS_, vol. 111, no. 24 (17 June 2014): 8788-8790.  
- Tony D. Sampson, Stephen Maddison, Darren Ellis, eds.,  _Affect and Social Media: Emotion, Media, Anxiety and Contagion_. London and New York: Rowman & Littlefield, 2018.  
- José van Dijck, _The Culture of Connectivity: A Critical History of Social Media_. Oxford: Oxford University Press, 2013.  
- [Evgeny Morozov](https://twitter.com/evgenymorozov), "[Critique of Techno-Feudal Reason](https://newleftreview.org/issues/ii133/articles/evgeny-morozov-critique-of-techno-feudal-reason)," _New Left Review_, 133/134 (Jan-Apr 2022).  
- Whitney Phillips and Ryan M. Milner, _You Are Here: A Field Guide for Navigating Polarized Speech, Conspiracy Theories, and Our Polluted Media Landscape_ (Cambridge: MIT Press, 2021).  
- [Shoshana Zuboff](https://shoshanazuboff.com), "[You Are the Object of a Secret Extraction Operation](https://www.nytimes.com/2021/11/12/opinion/facebook-privacy.html)," _New York Times_, 12 Nov 2021.

**Media**  
[Lingthusiasm](https://lingthusiasm.com/episodes) (Gretchen McCulloch's language podcast)

***  

## READING SCHEDULE  

**Week 1** M 05/16  

Topic: Quickstart  

Introductions - Course overview and logistics - Assignments

***  

**Week 2** M 05/23  

Topic: Disposession

- [Shoshana Zuboff](https://shoshanazuboff.com), "[You Are the Object of a Secret Extraction Operation](https://www.nytimes.com/2021/11/12/opinion/facebook-privacy.html)"  
- [Evgeny Morozov](https://twitter.com/evgenymorozov), "Critique of Techno-Feudal Reason" 

***  

**Week 3** M 05/30  

 Topic: Sharing  

- José van Dijck, _The Culture of Connectivity_: "Facebook and the Imperative of Sharing" (ch. 3)  
- Nicholas John, _The Age of Sharing_: "Introduction," "Sharing and the Internet" (ch. 3)

***  

**Week 4** M 06/06  

Topic: Affect  

- Nicholas John, _The Age of Sharing_: "Sharing our Feelings" (ch. 3)  
- Tony D. Sampson et al., _Affect and Social Media: Emotion, Media, Anxiety and Contagion_: "Introduction: On Affect, Social Media and Criticality"  
- Optional: Adam D.I. Kramer, et al., "[Experimental evidence of massive-scale emotional contagion through social networks](https://doi.org/10.1073/pnas.1320040111)," _PNAS_, vol. 111, no. 24 (17 June 2014): 8788-8790

***  

**Week 5** M 06/13  

Topic: Language

- [Gretchen McCulloch](https://gretchenmcculloch.com/), _Because Internet_: "Informal Writing," "Typographical Tone of Voice," "Emoji and Other Internet Gestures" (chs. 1, 4, 5)  

See also:  
- Geoffrey K. Pullum, "[Phrases for Lazy Writers in Kit Form](http://itre.cis.upenn.edu/%7Emyl/languagelog/archives/000061.html),"  _Language Log_, 27 Oct. 2003  
- Glen Whitman, "[Phrases for Lazy Writers in Kit Form Are the New Clichés](http://agoraphilia.blogspot.com/2004/01/phrases-for-lazy-writers-in-kit-form.html)," _Agoraphilia_, 14 Jan. 2004  
- Geoffrey K. Pullum, "[Snowclones: Lexicological Dating to the Second](http://itre.cis.upenn.edu/~myl/languagelog/archives/000350.html)," _Language Log_, 16 Jan. 2004
- Erin O'Connor, "[A bit of Language-Log-ish geekery](https://kirinqueen.livejournal.com/170517.html), _kirinqeen_ blog, 23 June 2005  
- [The Snowclones Database](https://snowclones.org/about/)  

***  

**Week 6** M 06/20  

Topic: Ecologies  

- Yves Citton, _The Ecology of Attention_: "Introduction: From Attention Economy to Attention Ecology"  
- Whitney Phillps and Ryan Milner, _You Are Here_: "Introduction: Mapping Network Pollution"  

***  

**Week 7** M 06/27  

Topic: Research papers

***

## WORKFLOW  

The above schedule is provisional; any changes to reading materials and/or assignment deadlines will be announced on Blackboard.

You are expected to complete reading and and discussion board assignments for each week the end of the day on Friday; discussion board question posts are due Friday evening on their the weekly  discussion boards.

## RULES & GRADING POLICY

**Responsibilities**  
You are required to use Blackboard during class. Course materials, reading assignments, due dates and outlines are posted on Blackboard and updated weekly: this means that assigned readings, assignments and due dates may change. You are responsible for reading any course announcements that are posted on Blackboard.

This class is a safe space from racist, sexist, or homophobic speech. If you do use hate speech in any forum associated with the class you will be subject to removal from class and possibly University disciplinary action. Keep it clean, polite and respectful on class time.

## ASSIGNMENTS & EVALUATION

Grades are based on:

- Midterm project description: 25% 
- Term project and presentation: 50% (various components across the semester - see below for details)
- Engagement and discussion board participation: 25%

Midterm Project Description: 25%

**Weekly Assignments**  
By the end of the day on Friday of each week, you will have completed one of the following:

- posted a short comment on and at least one question about the readings on the discussion board for the week
- submitted at least one response to at least one classmate on their question

It’s very important to keep up with and show that you are thinking about the readings and your responses to them.

On **Monday**  of each week, I will make an introductory post called an Agenda that introduces and contextualizes the reading assignments for the week, and identifies key themes, concepts, and/or issues to look out for as you read. Be sure to read the Monday agenda post before beginning the readings, and aim to complete them by around mid-week so that you can post your response and/or questions.

**Term Project**  
In week 2 you will submit a one-page project proposal, using the proposal template I’ll provide on Blackboard, on a topic relevant to the course that is of interest to you. This is worth 5% of your final grade.

You're required to discuss your proposal with me before submitting it. I will provide suggestions for research and development, along with helping you refine your topic and project deliverable. A discussion board will be available for you to submit ideas and discuss this with us so all of us can talk about your idea. 

Deliverables for the term project may include research papers, fieldwork reports, media creations, app/software design, or other things in consultation with me.

In week 4 you will submit a project progress report. This will focus on what you’ve done to meet the goals you set out in your proposal and what you need to do to complete successfully. This will be worth 5% of your final grade.

In week 7 you will deliver an audiovisual presentation on your project. The presentation should address what your project was about, why you chose it, the significance of the topic itself, how you went about investigating it, and what you concluded. This will be worth 5% of your final grade.  

To do this in PowerPoint: There should be a menu called “Slide Show.” On this menu, there’s a choice called “Slide transition (or just Transitions) . . . ” When you select it, you’ll see options for advancing the slide. Clear the check box beside “On Mouse Click,” and put (for example) “20″ in the box: “Automatically after seconds.”

Final presentations are hard. Rehearse, and then rehearse a lot more. I will book a time for rehearsals the week before presentation day. Attendance will be optional but strongly encouraged.

In week 7 you will also submit your paper. This will be worth 20% of your final grade.

**Discussion board questions**  

For the weeks specified on the schedule (pay careful attention!):

- by the end of the day on Friday each week post one substantive  question or comment related to the reading assignments for that  week. You should also submit at least one comment in response to posts by other students.  

The pupose of the question assignment is:

- to identify subjects/issues that are of interest to the entire group are there particular points or issues that consistently draw the class’s attention?
- to highlight aspects people might not have understood, or would like to see expressed more clearly during our class sessions.
- to help us to get to know _you_ better: are you the person who always asks about economics, or politics, or pop culture?

**Reading questions and responses**  
A _weak_ question is superficial, like a grade-school pop quiz question: “How does the author define X?” “How many copies of _Halo Reach_ were sold last year?” Weak questions have answers already in the material or are stock questions that potentially apply to anything: “Isn’t this bad for kids?”

A _good_ question calls for explanation or clarification: “Does Huizinga mean that games played for money aren’t games at all, or that they somehow stop being games when people get paid?”

An _excellent_ question link the reading to something else: “How does Huizinga’s attitude towards being paid to play relate to the role of amateurism in the Olympics and European aristocratic attitudes towards labor?”

A sentence or two is fine. You won’t get more credit for more words: concision and clarity are good things.

Below are some examples of questions from a previous class (on games studies) that represent “good” and “excellent” questions.

_Example #1:_  
“I want to primarily focus on "Bow, N****". How has the internet and by extension online gaming allowed for individuals to express racial views that are considered socially unacceptable? Do these people truly feel this way or is there some sort of stimulus that promotes this usage online?”

_Example #2_  
“I'm talking about Alter Ego.	The more options and choices that were presented, the more unrealistic portions of the game seemed.	At what point do we sacrifice realism in favor of control over the story? And at what point do we sacrifice control for the sake of realism? In my experience some of the best entertainment has come from finding the proper balance of these two, be it in a book, video game, or other form of media	It is this choice that leads to the complexity and realism in life that I don't think video games are able to capture in its complexity and nuances.

***  

## GCE LEARNING COMPETENCIES

**Critical Thinking & Problem Solving**  
The exam and term project formats are designed to confront students with a case drawn from current events in order to demonstrate their ability to apply theories, diagnose problems, and suggest solutions, both in a real-time, in-class exercise and over the course of the term in a more deliberative manner. In-class discussion focuses on students’ developing and defending personal views on key issues based upon evidence and theoretical frames.

**Communication**  
Students are encouraged to develop strengths in both written and oral communication, both deliberative and spontaneous, while the grading rubric recognizes that students have different strengths and comfort levels across media of expression. The format of the final presentation places a premium on conciseness, mastery of the material to be presented, and audience impact.

**Ethical Decision Making**  
This course examines the ethical underpinnings of technology design and use. It actively encourages students to discern and critique the ethical components of technology and to assert their own ethical values in technological analysis. The exams in particular call upon students to articulate an ethical and theoretical underpinning for their diagnoses of current problems and advocacy of solutions to those problems.

**Global Awareness**  
This course addresses the impact of technologies at the global scale, introduces concepts of global technological governance, and provides a range of readings and guest speakers from outside the US.

**Civic Engagement**  
This course does not call upon students to demonstrate civic engagement. Rather, it provides tools of critical thinking, ability to recognize global and local impacts, and the articulation of personal political lenses based upon theoretical frameworks and data analysis, in order to empower students with the tools for informed and effective engagement with the impacts of technologies at local, national, and global levels.

[This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License](http://creativecommons.org/licenses/by-nc/4.0/)

## BIBLIOGRAPHY  
  
A: = [Audiobook](https://audible.com)

danah boyd, _It’s Complicated: The Social Lives of Networked Teens_ (New Haven: Yale University Press, 2014).

Finn Brunton and Helen Nissenbaum, _Obfuscation: A User’s Guide for Privacy and Protest_ (Cambridge: MIT Press, 2016).

Gabriella Coleman, _Hacker, Hoaxer, Whistleblower, Spy: The Many Faces of Anonymous_ (London and New York: Verso, 2014).

David Craig, Jian Lin, and Stuart Cunningham, _Wanghong as Social Media Entertainment in China_. Palgrave Studies in Globalization, Culture and Society (London: Palgrave, 2021).

Stuart Cunningham and David Craig, _Social Media Entertainment: The New Intersection of Hollywood and Silicon Valley_ (New York: NYU Press, 2021).

---, eds. _Creator Culture: An Introduction to Global Social Media Entertainment_ (New York: New York University Press, 2021).

Eric Gordon and Adriana de Souza e Silva, _Net Locality: Why Location Matters in a Networked World_ (Chichester, West Sussex, UK: Wiley-Blackwell, 2011).

Byung-Chul Han, _In The Swarm: Digital Prospects_ (Cambridge: MIT Press, 2017).

Sarah J. Jackson, Moya Bailey, et al., _#HashtagActivism: Networks of Race and Gender Justice_ (Cambridge: MIT Press, 2020).

Lori Kido Lopez, _Race and Media: Critical Approaches_ (New York: New York University Press, 2020).

Lev Manovich, _Instagram and Contemporary Image_ (2015-17).

--\- _Cultural Analytics_ (Cambridge: MIT Press, 2020).

Gretchen McCulloch, _Because Internet: Understanding the New Rules of Language_ (New York: Riverhead Books, 2019).

Angela Nagle, _Kill All Normies: Online Culture Wars From 4Chan and Tumblr to Trump and the Alt-Right_ (Alresford, Hampshire, UK: Zero Books, 2017).

Whitney Phillips, _This Is Why We Can't Have Nice Things: Mapping the Relationship between Online Trolling and Mainstream Culture_ (Cambridge: MIT Press, 2015).

Whitney Phillips and Ryan M. Milner, _You Are Here: A Field Guide for Navigating Polarized Speech, Conspiracy Theories, and Our Polluted Media Landscape_ (Cambridge: MIT Press, 2021).

Zoë Quinn, _Crash Override: How Gamergate (Nearly) Destroyed My Life, and How We Can Win the Fight Against Online Hate_ (New York: PublicAffairs, 2017).

Jon Ronson, _So You've Been Publicly Shamed_ ( New York: Riverhead Books, 2015).

Kai Strittmatter, _We Have Been Harmonized: Life in China's Surveillance State_ (New York: HarperCollins, 2020).

Zeynep Tufekci, _Twitter and Tear Gas: The Power and Fragility of Networked Protest_ (New Haven: Yale University Press, 2017).

Siva Vaidyanathan, _Antisocial Media: How Facebook Disconnects Us and Undermines Democracy_ (Oxford: Oxford University Press, 2018).

***

## LATE POLICY

Assignments that are late will lose 1/2 of a grade per day, beginning at the end of class and including weekends and holidays. This means that a paper, which would have received an A if it was on time, will receive a B+ the next day, B- for two days late, and so on. Time management, preparation for our meetings, and timely submission of your work comprise a significant dimension of your professionalism. As such, your work must be completed by the beginning of class on the day it is due. If you have a serious problem that makes punctual submission impossible, you must discuss this matter with me before the due date so that we can make alternative arrangements. Because you are given plenty of time to complete your work, and major due dates are given to you well in advance, last minute problems should not preclude handing in assignments on time.

***

## MANDATORY REPORTER
Fitchburg State University is committed to providing a safe learning environment for all students that is free of all forms of discrimination and harassment. Please be aware all FSU faculty members are “mandatory reporters,” which means that if you tell me about a situation involving sexual harassment, sexual assault, dating violence, domestic violence, or stalking, I am legally required to share that information with the Title IX Coordinator. If you or someone you know has been impacted by sexual harassment, sexual assault, dating or domestic violence, or stalking, FSU has staff members trained to support you. If you or someone you know has been impacted by sexual harassment, sexual assault, dating or domestic violence, or stalking, please visit [http://fitchburgstate.edu/titleix](http://fitchburgstate.edu/titleix) to access information about university support and resources.

***

## HEALTH
[Health Services](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Fhealth-services%2F&sa=D&sntz=1&usg=AFQjCNEw5V0i0hL5DVO5b43gejNNaAt4ig)

Hours: Monday-Friday 8:30AM-5PM
Location: Ground Level of Russell Towers (across from the entrance of Holmes Dining Hall) Phone: (978) 665-3643/3894

[Counseling Services](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Fcounseling-services%2F&sa=D&sntz=1&usg=AFQjCNEYiS4EmSvWerpp2bKr5lTpouPuqQ)

The Counseling Services Office offers a range of services including individual, couples and group counseling, crisis intervention, psychoeducational programming, outreach ALTERNATIVE ECOSYSTEMSs, and community referrals. Counseling services are confidential and are offered at no charge to all enrolled students. Staff at Counseling Services are also available for consultation to faculty, staff and students. Counseling Services is located in the Hammond, 3rd Floor, Room 317.

[Fitchburg Anti-Violence Education (FAVE)](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Ffitchburg-anti-violence-education%2F&sa=D&sntz=1&usg=AFQjCNFi5qy-wunMxX-hoWbA9YwT8aa4Ig)

FAVE collaborates with a number of community partners (e.g., YWCA Domestic Violence Services, Pathways for Change) to meet our training needs and to link survivors with community based resources. This site also features [resources](http://www.google.com/url?q=http%3A%2F%2Fwww.fitchburgstate.edu%2Foffices-services-directory%2Ffitchburg-anti-violence-education%2Ffitchburg-anti-violence-education-resources%2F&sa=D&sntz=1&usg=AFQjCNF9KZ2O1AvPMLJTHdNg1DfmYYtgog) for help or information about dating violence, domestic violence, sexual assault and stalking. If you or someone you know is in an abusive relationship or has been a victim of sexual assault, there are many places to go for help. Many can be accessed 24 hours a day, seven days a week, 365 days a year. On campus, free and confidential support is provided at both Counseling Services and Health Services.

_Community Food Pantry_
Food insecurity is a growing issue and it certainly can affect student learning. The ability to have access to nutritious food is incredibly vital. The Falcon Bazaar, located in Hammond G 15, is stocked with food, basic necessities, and can provide meal swipes to support all Fitchburg State students experiencing food insecurity for a day or a semester.

The university continues to partner with Our Father's House to support student needs and access to food and services. All Fitchburg State University students are welcome at the Our Father’s House Community Food Pantry. This Pantry is located at the Faith Christian Church at 40 Boutelle St., Fitchburg, MA and is open from 5-7pm. Each “household” may shop for nutritious food once per month by presenting a valid FSU ID.

***

## ACADEMIC INTEGRITY
The University “Academic Integrity” policy can be found online at [http:// www.fitchburgstate.edu/offices-services-directory/office-of-student-conductmediation-education/academic-integrity/.](http://www.fitchburgstate.edu/offices-services-directory/office-of-student-conduct-mediation-education/academic-integrity/) Students are expected to do their own work. Plagiarism and cheating are inexcusable. Any instance of plagiarism or cheating will automatically result in a zero on the assignment and may be reported the Office of Student and Academic Life at the discretion of the instructor.

Plagiarism includes, but is not limited to:
-   Using papers or work from another class.
-   Using another student's paper or work from any class.
-   Copying work or a paper from the Internet.
-   The egregious lack of citing sources or documenting research.
    
_If you're not clear on what is or is not plagiarism, ASK. The BEST case scenario if caught is a zero on that assignment, and ignorance of what does or does not count is not an excuse. That being said, I'm a strong supporter of_ _[Fair Use](https://en.wikipedia.org/wiki/Fair_Use) doctrine. Just attribute what you use--and, again, ASK if there's any doubt._

***

## AMERICANS WITH DISABILITIES ACT (ADA)
If you need course adaptations or accommodations because of a disability, if you have emergency medical information to share with the instructor, or if you need special arrangements in case the building must be evacuated, please inform the faculty member as soon as possible.

***

## TECHNOLOGY
At some point during the semester you will likely have a problem with technology. Your laptop will crash; your iPad battery will die; a recording you make will disappear; you will accidentally delete a file; the wireless will go down at a crucial time. These, however, are inevitabilities of life, not emergences. Technology problems are not excuses for unfinished or late work. Bad things may happen, but you can protect yourself by doing the following:

-   Plan ahead: A deadline is the last minute to turn in material. You can start—and finish—early, particularly if challenging resources are required, or you know it will be time consuming to finish this project.
    
-   Save work early and often: Think how much work you do in 10 minutes. I auto save every 2 minutes.
    
-   Make regular backups of files in a different location: Between Box, Google Drive, Dropbox, and iCloud, you have ample places to store and backup your materials. Use them.
    
-   Save drafts: When editing, set aside the original and work with a copy.
    
-   Practice safe computing: On your personal devices, install and use software to control viruses and malware.
    
  ***

## GRADING POLICY
Grading for the course will follow the FSU grading policy below:

4.0: 95-100  
3.7: 92-94  
3.5: 89-91  
3.3: 86-88  
3.0: 83-85  
2.7: 80-82  
2.5: 77-79  
2.3: 74-76  
2.0: 71-73  
0.0: < 70  

***

## ACADEMIC RESOURCES

[Writing Center](http://www.fitchburgstate.edu/offices-services-directory/tutor-center/writing-help/)

[Academic Policies](http://catalog.fitchburgstate.edu/content.php?catoid=13&navoid=851)

[Disability Services](http://www.fitchburgstate.edu/offices-services-directory/disability-services/)

[Fitchburg State Alert system for emergencies, snow closures/delays, and faculty absences](https://www.getrave.com/login/fitchburgstate/)

[University Career Services](http://www.fitchburgstate.edu/offices-services-directory/career-counseling-and-advising/careerservices/)

***

